@baseUrl = http://localhost:8080
@colaboradorId = 1
@teamId = 1
@projetoId = 1

### Listar colaboradores
GET {{baseUrl}}/colaboradores

###

### Buscar colaborador
GET {{baseUrl}}/colaboradores/{{colaboradorId}}

###

### Adicionar colaborador à Team
POST {{baseUrl}}/teams/{{teamId}}/colaboradores/{{colaboradorId}}

###

### Remover colaborador da Team
DELETE {{baseUrl}}/teams/{{teamId}}/colaboradores/{{colaboradorId}}

###

### Adicionar colaborador como responsável
POST {{baseUrl}}/projetos/{{projetoId}}/responsaveis/{{colaboradorId}}